<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="SuMulms" targetNamespace="http://tempuri.org/SuMulms" xmlns="http://tempuri.org/SuMulms" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tempuri.org/SuMulms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:documentation>
        <wsdl:appinfo source="WMQI_APPINFO">
            <MRWSDLAppInfo imported="true">
                <generatedXSD location="SuMulmsService_InlineSchema1.xsd"/>
                <binding hasEncoding="false" imported="true" name="SuMulmsSOAP_HTTP_Binding" originalBindingStyle="document"/>
            </MRWSDLAppInfo>
        </wsdl:appinfo>
    </wsdl:documentation>
    <wsdl:types>
        <xsd:schema targetNamespace="http://tempuri.org/SuMulms" xmlns:mrm="http://tempuri.org/SuMulms">
            <xsd:include schemaLocation="SuMulmsService_InlineSchema1.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="OpeSuMul_in">
        <wsdl:part element="SuMulInput" name="SuMulInput"/>
    </wsdl:message>
    <wsdl:message name="OpeSuMul_out">
        <wsdl:part element="SuMulOutput" name="SuMulOutput"/>
    </wsdl:message>
    <wsdl:message name="OpeSuMul_fault1">
        <wsdl:part element="SuMulMess" name="SuMulMess"/>
    </wsdl:message>
    <wsdl:portType name="SuMulmsPortType">
        <wsdl:operation name="OpeSuMul">
            <wsdl:input message="OpeSuMul_in" name="OpeSuMul_Input"/>
            <wsdl:output message="OpeSuMul_out" name="OpeSuMul_Output"/>
            <wsdl:fault message="OpeSuMul_fault1" name="OpeSuMul_Fault"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SuMulmsSOAP_HTTP_Binding" type="SuMulmsPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="OpeSuMul">
            <soap:operation soapAction="SuMulAction"/>
            <wsdl:input name="OpeSuMul_Input">
                <soap:body parts="SuMulInput" use="literal"/>
            </wsdl:input>
            <wsdl:output name="OpeSuMul_Output">
                <soap:body parts="SuMulOutput" use="literal"/>
            </wsdl:output>
            <wsdl:fault name="OpeSuMul_Fault">
                <soap:fault name="OpeSuMul_Fault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="SuMulmsSOAP_HTTP_Service">
        <wsdl:port binding="SuMulmsSOAP_HTTP_Binding" name="SuMulmsSOAP_HTTP_Port">
            <soap:address location="http://localhost:7800/SuMulmsSOAP_HTTP_Service"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>